# path="/media/hamza/DATA/Data/tum"
path="/cluster/home/javedh/tum2"
debug_path="../../debug_folder/freeze_weights"
stride=0
batch=2
seq_dilation=100
freeze="y"
scale=1
sequence="rgbd_dataset_freiburg2_xyz"

bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --sequences ${sequence} --seq_length 10 --batch_size ${batch} --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze y
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --sequences ${sequence} --seq_length 10 --batch_size ${batch} --debug_path ${debug_path} --model_name ${sequence}_10dil_nofreeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze n
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --sequences ${sequence} --seq_length 10 --batch_size ${batch} --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_${stride}_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze y
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --sequences ${sequence} --seq_length 10 --batch_size ${batch} --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_${stride}_morephoto --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze y
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --sequences ${sequence} --seq_length 10 --batch_size ${batch} --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_${stride}_geomonly --loss_photo_factor 0 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze y
