path="/media/hamza/DATA/Data/tum"
path="/cluster/home/javedh/tum2"
debug_path="../../debug_folder/alphas3_cluster"
stride=0
seq_dilation=100
freeze="y"
scale=1
sequence="rgbd_dataset_freiburg2_xyz"

bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_5dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 5 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_15dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 15 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_25dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 25 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_50dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 50 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_75dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 75 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --odometry icp --train_odometry gt --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_100dil_freeze_${stride} --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 100 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}


# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_5dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 5 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_15dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 15 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_25dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 25 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_50dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 50 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_75dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 75 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_100dil_freeze_photo_only_${stride} --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 100 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}


# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_5dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 5 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 10 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_15dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 15 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_25dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 25 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_50dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 50 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_75dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 75 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_100dil_freeze_photomore_${stride} --loss_photo_factor 2 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale ${scale} --seq_dilation 100 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}


# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_5dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 5 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_10dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 10 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_15dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 15 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_25dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 25 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_50dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 50 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_75dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 75 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}
# bsub -R "rusage[mem=8096, ngpus_excl_p=1]" python3 pointfusion_scsfm.py --dataset tum --dataset_path $path --odometry gt --sequences ${sequence} --seq_length 10 --batch_size 5 --debug_path ${debug_path} --model_name ${sequence}_100dil_freeze_photoonly --loss_photo_factor 1 --loss_geom_factor 0 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 75 --max_scale 4 --seq_dilation 100 --max_num_batches 2 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous --seq_stride ${stride} --freeze ${freeze}