# xyzs
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_xyz --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name xyzs_011_previous_scale1_dil50 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 50 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_xyz --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name xyzs_012_previous_scale1_dil25 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 25 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_xyz --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name xyzs_013_previous_scale1_dil10 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 10 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_xyz --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name xyzs_014_previous_scale1_dil1 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 1 --max_num_batches 1 --seq_start 1 --seq_end 2002 --num_epochs 300 --projection_mode previous"

#slams
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_pioneer_slam --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name slams_011_previous_scale1_dil5 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 5 --max_num_batches 1 --seq_start 369 --seq_end 571 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_pioneer_slam --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name slams_012_previous_scale1_dil3 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 3 --max_num_batches 1 --seq_start 369 --seq_end 571 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg2_pioneer_slam --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name slams_013_previous_scale1_dil1 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 1 --max_num_batches 1 --seq_start 369 --seq_end 571 --num_epochs 300 --projection_mode previous"

# desks
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg1_desk --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name desks_011_previous_scale1_dil3 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 3 --max_num_batches 1 --seq_start 353 --seq_end 495 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg1_desk --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name desks_012_previous_scale1_dil1 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 1 --max_num_batches 1 --seq_start 353 --seq_end 495 --num_epochs 300 --projection_mode previous"

# rpys
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg1_rpy --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name rpys_011_previous_scale1_dil3 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 3 --max_num_batches 1 --seq_start 310 --seq_end 492 --num_epochs 300 --projection_mode previous"
bsub -R "rusage[mem=8096, ngpus_excl_p=1]" "python pointfusion_scsfm.py --dataset tum --dataset_path ../sample_data/dataset_TUM --odometry icp --train_odometry gt --sequences rgbd_dataset_freiburg1_rpy --seq_length 10 --batch_size 2 --debug_path ../debug_folder --model_name rpys_012_previous_scale1_dil1 --loss_photo_factor 1 --loss_geom_factor 0.5 --loss_smooth_factor 0.1 --loss_cons_factor 0 --loss_gt_factor 0 --log_freq 30 --max_scale 1 --seq_dilation 1 --max_num_batches 1 --seq_start 310 --seq_end 492 --num_epochs 300 --projection_mode previous"

